version: '3'
services:
  # Laravel Service
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql:3306
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  # MySQL Service
  mysql:
    image: mariadb:10.5.19
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}_toor
      
  # NextJS Service
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: npm run dev
    volumes:
      - ./nextjs:/app
      # Add any additional volumes if needed
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development


  # Nginx Service
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
    depends_on:
      - laravel
      - nextjs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - 8080:80
    depends_on:
        - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      #MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}_toor

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"