version: '3'
services:
  # Laravel Service
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  # MySQL Service
  mysql:
    image: mariadb:10.5.19
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=laravel
      #- MYSQL_USERNAME=root
      - MYSQL_root_PASSWORD=root
      
  # NextJS Service
  nextjs:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: npm run dev
    volumes:
      - ./nextjs:/app
      # Add any additional volumes if needed
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development


  # Nginx Service
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8088:80
    depends_on:
      - laravel
      - nextjs

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: root
        PMA_PORT: 3306
        PMA_ARBITRARY: 1